import { MigrationInterface, QueryRunner } from "typeorm";

export class InitMigration1763014172027 implements MigrationInterface {
    name = 'InitMigration1763014172027'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "menu_categories" ("id" BIGSERIAL NOT NULL, "tenant_id" bigint NOT NULL, "name" character varying(100) NOT NULL, "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "tenantId" bigint, CONSTRAINT "PK_124ae987900336f983881cb04e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_menu_categories_tenant" ON "menu_categories" ("tenant_id", "display_order") `);
        await queryRunner.query(`CREATE TABLE "tables" ("id" BIGSERIAL NOT NULL, "tenant_id" bigint NOT NULL, "table_number" character varying(50) NOT NULL, "table_type" character varying(20) NOT NULL DEFAULT 'table', "capacity" integer NOT NULL DEFAULT '4', "qr_code_url" character varying(500), "qr_code_data" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_tables_tenant_number" UNIQUE ("tenant_id", "table_number"), CONSTRAINT "PK_7cf2aca7af9550742f855d4eb69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_tables_tenant" ON "tables" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" BIGSERIAL NOT NULL, "tenant_id" bigint NOT NULL, "table_id" bigint NOT NULL, "session_token" character varying(255) NOT NULL, "guest_count" integer NOT NULL DEFAULT '1', "started_at" TIMESTAMP NOT NULL DEFAULT now(), "expires_at" TIMESTAMP, "is_active" boolean NOT NULL DEFAULT true, "closed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_sessions_token" UNIQUE ("session_token"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_sessions_active" ON "sessions" ("is_active", "expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_sessions_token" ON "sessions" ("session_token") `);
        await queryRunner.query(`CREATE INDEX "idx_sessions_tenant_table" ON "sessions" ("tenant_id", "table_id") `);
        await queryRunner.query(`CREATE TABLE "payments" ("id" BIGSERIAL NOT NULL, "tenant_id" bigint NOT NULL, "order_id" bigint NOT NULL, "payment_method" character varying(50) NOT NULL DEFAULT 'cash', "amount" numeric(10,2) NOT NULL DEFAULT '0.00', "status" character varying(20) NOT NULL DEFAULT 'pending', "external_transaction_id" character varying(255), "payment_details" jsonb, "paid_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_payments_status" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_external_txn" ON "payments" ("external_transaction_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_tenant_order" ON "payments" ("tenant_id", "order_id") `);
        await queryRunner.query(`CREATE TABLE "orders" ("id" BIGSERIAL NOT NULL, "tenant_id" bigint NOT NULL, "session_id" bigint NOT NULL, "table_id" bigint NOT NULL, "order_number" character varying(50) NOT NULL, "guest_count" integer NOT NULL DEFAULT '1', "total_amount" numeric(10,2) NOT NULL DEFAULT '0.00', "status" character varying(20) NOT NULL DEFAULT 'pending', "payment_status" character varying(20) NOT NULL DEFAULT 'unpaid', "notes" text, "ordered_at" TIMESTAMP NOT NULL DEFAULT now(), "completed_at" TIMESTAMP, "version" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_orders_tenant_order_number" UNIQUE ("tenant_id", "order_number"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_orders_payment" ON "orders" ("tenant_id", "payment_status") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_table" ON "orders" ("table_id", "ordered_at") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_session" ON "orders" ("session_id") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_tenant_status" ON "orders" ("tenant_id", "status", "ordered_at") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" BIGSERIAL NOT NULL, "order_id" bigint NOT NULL, "menu_id" bigint NOT NULL, "menu_name" character varying(255) NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "unit_price" numeric(10,2) NOT NULL DEFAULT '0.00', "subtotal" numeric(10,2) NOT NULL DEFAULT '0.00', "status" character varying(20) NOT NULL DEFAULT 'pending', "preparation_area" character varying(50) NOT NULL DEFAULT 'kitchen', "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_order_items_area" ON "order_items" ("preparation_area", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_order_items_status" ON "order_items" ("order_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_order_items_order" ON "order_items" ("order_id") `);
        await queryRunner.query(`CREATE TABLE "menus" ("id" BIGSERIAL NOT NULL, "tenant_id" bigint NOT NULL, "category_id" bigint, "sku" character varying(100), "name" character varying(255) NOT NULL, "description" text, "price" numeric(10,2) NOT NULL DEFAULT '0.00', "image_url" character varying(500), "allergen_info" text, "preparation_area" character varying(50) NOT NULL DEFAULT 'kitchen', "preparation_time_minutes" integer NOT NULL DEFAULT '15', "is_available" boolean NOT NULL DEFAULT true, "stock_quantity" integer, "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3fec3d93327f4538e0cbd4349c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_menus_availability" ON "menus" ("tenant_id", "is_available", "is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_menus_tenant_category" ON "menus" ("tenant_id", "category_id") `);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" BIGSERIAL NOT NULL, "name" character varying(255) NOT NULL, "subdomain" character varying(100), "default_language" character varying(10) NOT NULL DEFAULT 'ja', "currency" character varying(10) NOT NULL DEFAULT 'THB', "timezone" character varying(50) NOT NULL DEFAULT 'Asia/Bangkok', "subscription_plan" character varying(50) NOT NULL DEFAULT 'basic', "subscription_status" character varying(20) NOT NULL DEFAULT 'active', "monthly_fee" numeric(10,2) NOT NULL DEFAULT '3000', "max_tables" integer NOT NULL DEFAULT '30', "address" text, "phone" character varying(20), "email" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_21bb89e012fa5b58532009c1601" UNIQUE ("subdomain"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_tenants_status" ON "tenants" ("subscription_status") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" BIGSERIAL NOT NULL, "tenant_id" bigint NOT NULL, "cognito_user_id" character varying, "username" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "full_name" character varying(255), "role" character varying(50) NOT NULL DEFAULT 'staff', "language_preference" character varying(10) NOT NULL DEFAULT 'ja', "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_users_cognito_id" UNIQUE ("cognito_user_id"), CONSTRAINT "uq_users_tenant_email" UNIQUE ("tenant_id", "email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_users_tenant" ON "users" ("tenant_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" BIGSERIAL NOT NULL, "user_id" bigint NOT NULL, "role_name" character varying(50) NOT NULL, "permissions" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_roles_user" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "payment_webhooks" ("id" BIGSERIAL NOT NULL, "payment_id" bigint, "webhook_event" character varying(100) NOT NULL, "payload" jsonb NOT NULL, "headers" jsonb, "signature" character varying(500), "is_verified" boolean NOT NULL DEFAULT false, "processed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_676045943e5ab1ef7cdaa86a5b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_payment_webhooks_event" ON "payment_webhooks" ("webhook_event", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_payment_webhooks_payment" ON "payment_webhooks" ("payment_id") `);
        await queryRunner.query(`CREATE TABLE "order_status_history" ("id" BIGSERIAL NOT NULL, "order_id" bigint NOT NULL, "order_item_id" bigint, "previous_status" character varying(20), "new_status" character varying(20) NOT NULL, "changed_by_user_id" bigint, "changed_by_role" character varying(50), "notes" text, "changed_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e6c66d853f155531985fc4f6ec8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_order_status_history_item" ON "order_status_history" ("order_item_id") `);
        await queryRunner.query(`CREATE INDEX "idx_order_status_history_order" ON "order_status_history" ("order_id", "changed_at") `);
        await queryRunner.query(`CREATE TABLE "menu_translations" ("id" BIGSERIAL NOT NULL, "menu_id" bigint NOT NULL, "language_code" character varying(10) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_menu_translations_menu_lang" UNIQUE ("menu_id", "language_code"), CONSTRAINT "PK_40c4d4963d02d71fb901cf697e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_menu_translations_menu_lang" ON "menu_translations" ("menu_id", "language_code") `);
        await queryRunner.query(`CREATE TABLE "carts" ("id" BIGSERIAL NOT NULL, "session_id" bigint NOT NULL, "tenant_id" bigint NOT NULL, "total_amount" numeric(10,2) NOT NULL DEFAULT '0.00', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_carts_session" UNIQUE ("session_id"), CONSTRAINT "PK_b5f695a59f5ebb50af3c8160816" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_carts_tenant" ON "carts" ("tenant_id") `);
        await queryRunner.query(`ALTER TABLE "menu_categories" ADD CONSTRAINT "FK_301bc57e6a2d1714c6bad86fdad" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tables" ADD CONSTRAINT "FK_4d371f09bf8805550024558ba4b" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_22aa22eb69a1e6826a1f58902d1" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_e5e5afb9b66988bf1178b718a94" FOREIGN KEY ("table_id") REFERENCES "tables"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_9109b53fca5cef7720aca72974d" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b2f7b823a21562eeca20e72b006" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_527dd6efd5f3402f729c6b3e826" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_4a911af0c90c68d0d98e491cc53" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_3d36410e89a795172fa6e0dd968" FOREIGN KEY ("table_id") REFERENCES "tables"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_564d2ba92c6bc3ec79c874e1458" FOREIGN KEY ("menu_id") REFERENCES "menus"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menus" ADD CONSTRAINT "FK_b92e24f01e587cfd77b17217a4a" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menus" ADD CONSTRAINT "FK_83b2cc4e4e8467ea40e5cf860f3" FOREIGN KEY ("category_id") REFERENCES "menu_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_109638590074998bb72a2f2cf08" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_webhooks" ADD CONSTRAINT "FK_bcfbf7e2e64b466888b6ec07aa1" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_1ca7d5228cf9dc589b60243933c" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_8a1a732e06a3031806d00d9a41a" FOREIGN KEY ("order_item_id") REFERENCES "order_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_965678b54f0a0361ca72c541b20" FOREIGN KEY ("changed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_translations" ADD CONSTRAINT "FK_22d219b4f9b1aaf0131736e3d0d" FOREIGN KEY ("menu_id") REFERENCES "menus"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_f57f87515b7c25718dc380c69c7" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_846bcf9b09d81d7e8b67096ef38" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_846bcf9b09d81d7e8b67096ef38"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_f57f87515b7c25718dc380c69c7"`);
        await queryRunner.query(`ALTER TABLE "menu_translations" DROP CONSTRAINT "FK_22d219b4f9b1aaf0131736e3d0d"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_965678b54f0a0361ca72c541b20"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_8a1a732e06a3031806d00d9a41a"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_1ca7d5228cf9dc589b60243933c"`);
        await queryRunner.query(`ALTER TABLE "payment_webhooks" DROP CONSTRAINT "FK_bcfbf7e2e64b466888b6ec07aa1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_109638590074998bb72a2f2cf08"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP CONSTRAINT "FK_83b2cc4e4e8467ea40e5cf860f3"`);
        await queryRunner.query(`ALTER TABLE "menus" DROP CONSTRAINT "FK_b92e24f01e587cfd77b17217a4a"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_564d2ba92c6bc3ec79c874e1458"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_3d36410e89a795172fa6e0dd968"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_4a911af0c90c68d0d98e491cc53"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_527dd6efd5f3402f729c6b3e826"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b2f7b823a21562eeca20e72b006"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_9109b53fca5cef7720aca72974d"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_e5e5afb9b66988bf1178b718a94"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_22aa22eb69a1e6826a1f58902d1"`);
        await queryRunner.query(`ALTER TABLE "tables" DROP CONSTRAINT "FK_4d371f09bf8805550024558ba4b"`);
        await queryRunner.query(`ALTER TABLE "menu_categories" DROP CONSTRAINT "FK_301bc57e6a2d1714c6bad86fdad"`);
        await queryRunner.query(`DROP INDEX "public"."idx_carts_tenant"`);
        await queryRunner.query(`DROP TABLE "carts"`);
        await queryRunner.query(`DROP INDEX "public"."idx_menu_translations_menu_lang"`);
        await queryRunner.query(`DROP TABLE "menu_translations"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_status_history_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_status_history_item"`);
        await queryRunner.query(`DROP TABLE "order_status_history"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payment_webhooks_payment"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payment_webhooks_event"`);
        await queryRunner.query(`DROP TABLE "payment_webhooks"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_roles_user"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_tenant"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tenants_status"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP INDEX "public"."idx_menus_tenant_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_menus_availability"`);
        await queryRunner.query(`DROP TABLE "menus"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_items_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_items_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_items_area"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_tenant_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_session"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_table"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_payment"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_tenant_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_external_txn"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_status"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_tenant_table"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_active"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tables_tenant"`);
        await queryRunner.query(`DROP TABLE "tables"`);
        await queryRunner.query(`DROP INDEX "public"."idx_menu_categories_tenant"`);
        await queryRunner.query(`DROP TABLE "menu_categories"`);
    }

}
